# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/coenraad/vibeprocess/vp-c

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/coenraad/vibeprocess/vp-c

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/coenraad/vibeprocess/vp-c/CMakeFiles /home/coenraad/vibeprocess/vp-c//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/coenraad/vibeprocess/vp-c/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named vp

# Build rule for target.
vp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 vp
.PHONY : vp

# fast build rule for target.
vp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vp.dir/build.make CMakeFiles/vp.dir/build
.PHONY : vp/fast

src/api.o: src/api.cpp.o
.PHONY : src/api.o

# target to build an object file
src/api.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vp.dir/build.make CMakeFiles/vp.dir/src/api.cpp.o
.PHONY : src/api.cpp.o

src/api.i: src/api.cpp.i
.PHONY : src/api.i

# target to preprocess a source file
src/api.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vp.dir/build.make CMakeFiles/vp.dir/src/api.cpp.i
.PHONY : src/api.cpp.i

src/api.s: src/api.cpp.s
.PHONY : src/api.s

# target to generate assembly for a file
src/api.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vp.dir/build.make CMakeFiles/vp.dir/src/api.cpp.s
.PHONY : src/api.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vp.dir/build.make CMakeFiles/vp.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vp.dir/build.make CMakeFiles/vp.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vp.dir/build.make CMakeFiles/vp.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/process.o: src/process.cpp.o
.PHONY : src/process.o

# target to build an object file
src/process.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vp.dir/build.make CMakeFiles/vp.dir/src/process.cpp.o
.PHONY : src/process.cpp.o

src/process.i: src/process.cpp.i
.PHONY : src/process.i

# target to preprocess a source file
src/process.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vp.dir/build.make CMakeFiles/vp.dir/src/process.cpp.i
.PHONY : src/process.cpp.i

src/process.s: src/process.cpp.s
.PHONY : src/process.s

# target to generate assembly for a file
src/process.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vp.dir/build.make CMakeFiles/vp.dir/src/process.cpp.s
.PHONY : src/process.cpp.s

src/procutil.o: src/procutil.cpp.o
.PHONY : src/procutil.o

# target to build an object file
src/procutil.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vp.dir/build.make CMakeFiles/vp.dir/src/procutil.cpp.o
.PHONY : src/procutil.cpp.o

src/procutil.i: src/procutil.cpp.i
.PHONY : src/procutil.i

# target to preprocess a source file
src/procutil.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vp.dir/build.make CMakeFiles/vp.dir/src/procutil.cpp.i
.PHONY : src/procutil.cpp.i

src/procutil.s: src/procutil.cpp.s
.PHONY : src/procutil.s

# target to generate assembly for a file
src/procutil.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vp.dir/build.make CMakeFiles/vp.dir/src/procutil.cpp.s
.PHONY : src/procutil.cpp.s

src/resource.o: src/resource.cpp.o
.PHONY : src/resource.o

# target to build an object file
src/resource.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vp.dir/build.make CMakeFiles/vp.dir/src/resource.cpp.o
.PHONY : src/resource.cpp.o

src/resource.i: src/resource.cpp.i
.PHONY : src/resource.i

# target to preprocess a source file
src/resource.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vp.dir/build.make CMakeFiles/vp.dir/src/resource.cpp.i
.PHONY : src/resource.cpp.i

src/resource.s: src/resource.cpp.s
.PHONY : src/resource.s

# target to generate assembly for a file
src/resource.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vp.dir/build.make CMakeFiles/vp.dir/src/resource.cpp.s
.PHONY : src/resource.cpp.s

src/state.o: src/state.cpp.o
.PHONY : src/state.o

# target to build an object file
src/state.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vp.dir/build.make CMakeFiles/vp.dir/src/state.cpp.o
.PHONY : src/state.cpp.o

src/state.i: src/state.cpp.i
.PHONY : src/state.i

# target to preprocess a source file
src/state.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vp.dir/build.make CMakeFiles/vp.dir/src/state.cpp.i
.PHONY : src/state.cpp.i

src/state.s: src/state.cpp.s
.PHONY : src/state.s

# target to generate assembly for a file
src/state.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/vp.dir/build.make CMakeFiles/vp.dir/src/state.cpp.s
.PHONY : src/state.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... vp"
	@echo "... src/api.o"
	@echo "... src/api.i"
	@echo "... src/api.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/process.o"
	@echo "... src/process.i"
	@echo "... src/process.s"
	@echo "... src/procutil.o"
	@echo "... src/procutil.i"
	@echo "... src/procutil.s"
	@echo "... src/resource.o"
	@echo "... src/resource.i"
	@echo "... src/resource.s"
	@echo "... src/state.o"
	@echo "... src/state.i"
	@echo "... src/state.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

